version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest@sha256:5145492f8a974d777e7ca6ee01032c476033388495f56eea06ab770e1d1e5c62
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api

  api:
    build: ./projects/api
    depends_on:
      - postgres
      - redis
    environment:
      # These env variables are necessary to let Nginx reverse proxy us.
      - VIRTUAL_HOST=api.margaret.com
      - VIRTUAL_PORT=8080

      # These env variables will be read from the host machine.
      - MIX_ENV

  web:
    build: ./projects/web
    environment:
      # These env variables are necessary to let Nginx reverse proxy us.
      - VIRTUAL_HOST=margaret.com
      - VIRTUAL_PORT=80

      # These env variables will be read from the host machine.
      - NODE_ENV

  ml:
    build: ./projects/ml


  postgres:
    image: postgres:10.3@sha256:453e3be1cecf030a4ee04225352e618bcacf822276a17a79a9b0f990cb8b4aef
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:4.0.10@sha256:e6683aa5b5f626004bde089e30ccefcf357c700a697f97fc85e9c1a241c60600
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
