version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest@sha256:3bfdbb899dc0214e00f3ac6002ef2c6cf6924c22a438e5f0dc08e30220ca8686
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api

  api:
    build: ./projects/api
    depends_on:
      - postgres
      - redis
    environment:
      # These env variables are necessary to let Nginx reverse proxy us.
      - VIRTUAL_HOST=api.margaret.com
      - VIRTUAL_PORT=8080

      # These env variables will be read from the host machine.
      - MIX_ENV

  web:
    build: ./projects/web
    environment:
      # These env variables are necessary to let Nginx reverse proxy us.
      - VIRTUAL_HOST=margaret.com
      - VIRTUAL_PORT=80

      # These env variables will be read from the host machine.
      - NODE_ENV

  ml:
    build: ./projects/ml


  postgres:
    image: postgres:10.3@sha256:e2688f79c920bbd5bcb8e1ed54aef522c7e93a1a5eab32e10b4b020d49b4b925
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:4.0.9@sha256:fed1e53de35ffdf2d9e95afd20df938e4790fb52bc5093987e6f6649bd413786
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
